Hector/feature/6.2 contacto
manuortegac/exercise-collaborative-html-website pull request #1
Opened 2021-01-15 00:02 UTC by codehsalas

Pendiente de revisión.

2021-01-15 00:25 UTC, manuortegac requested changes

2021-01-15 00:25 UTC, manuortegac commented on website1/templates/contact.html
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="an
Porque el link a bootstrap no se encuentra dentro de la etiqueta <head>. por favor corregir

2021-01-15 00:33 UTC, codehsalas commented on website1/templates/contact.html
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="an
Listo, corregido.

2021-01-15 15:08 UTC, aparral approved these changes

2021-01-15 15:36 UTC, NicolasArayaB approved these changes

2021-01-15 16:12 UTC, aparral requested changes
El link de bootstrap no debe ir en contact.html... solo se agrega en index.thml

2021-01-15 16:35 UTC, manuortegac requested changes
@codehsalas el archivo contact.html solo debe estar el HTML que genera el, portafolio. No debes agregar las etiquetas tampoco y tampoco . Solo la parte que dibuja el portafolio ya que este código se inserta en el index.html que tiene todo lo que necesitas

2021-01-15 21:47 UTC, codehsalas commented
> @codehsalas el archivo contact.html solo debe estar el HTML que genera el, portafolio. No debes agregar las etiquetas tampoco y tampoco . Solo la parte que dibuja el portafolio ya que este código se inserta en el index.html que tiene todo lo que necesitas

2021-01-15 21:48 UTC, codehsalas commented
Manu... no entendi que me mencionas sobre el portafolio...
Voy a retirar el link de Boostrap.
Saludos.

2021-01-16 00:04 UTC, codehsalas commented
> @codehsalas el archivo contact.html solo debe estar el HTML que genera el, portafolio. No debes agregar las etiquetas tampoco y tampoco . Solo la parte que dibuja el portafolio ya que este código se inserta en el index.html que tiene todo lo que necesitas

2021-01-16 00:04 UTC, closed without merging

2021-01-16 00:05 UTC, codehsalas commented
Manu
Acabo de modificar el archivo contact.html, retirando el head y el enlace a Bootstrap.
Favor revisar.
Saludos.