se crea container y se agrega imagen
manuortegac/exercise-collaborative-html-website pull request #10
Opened 2021-01-16 12:28 UTC by CablCode

se crea container y se agrega imagen

2021-01-16 13:24 UTC, NicolasArayaB commented
Hola! En service.html generaste toda la estructura de la pagina. El codigo va a ser insertado en una estructura ya definida, por lo que solo tienes que dejar el codigo que necesitas.

2021-01-16 16:08 UTC, francisco-correa reviewed
el código va bien con la imagen, pero falto redondearla
Recomendación similar a la Walter White

<img src="/website1/assets/img/1.jpg" **class="rounded-circle" alt="Walter White" width="250">**

2021-01-16 16:22 UTC, CablCode commented
Hola Francisco, si, lo agregue al CSS como border radius pero no se si lo pescó bien el html

2021-01-16 17:30 UTC, luisrcc approved these changes

2021-01-16 22:09 UTC, NicolasArayaB requested changes
Hay que corregir la ruta a la imagen, ya que index.html está en la carpeta website1, al poner los dos puntos ( .. )  subes un nivel y se pierde el enlace. Solo hay que dejar un punto para que funcione.

2021-01-18 12:10 UTC, francisco-correa approved these changes
la imagen esta al lado izquierdo, en forma redondeada

2021-01-18 12:49 UTC, NicolasArayaB approved these changes

2021-01-18 12:50 UTC, merged